### ISSUE TITLE
Request for alternative cloud access to preprocessed data

### ISSUE THREAD

**Issue by iminolee** [MrZihan/Sim2Real-VLN-3DFF#1]
Thank you for the inspired source.
I would like to request if you could provide a way to install the preprocessed data and checkpoints shared on **Baidu** through another cloud service.

**Comment by MrZihan** [comment]
Hi, another cloud drive is here [TeraBox](https://terabox.com/s/1fX5LApMdMHHIwrLIzqIbxA). 
If you have any other questions, feel free to ask.
